alias em='emacs -nw' 
alias sem='sudo emacs -nw'
alias ga='git add'
alias co='git checkout'
alias gp='git push'
alias gb='git branch'
alias gl='git log'
alias glp='git log --pretty=format:"%Cred%h%Creset - %Cgreen%an%Creset, %ar : %s"'
alias gs='git status'
alias gd='git diff'
alias gcm='git commit -m'
alias gpu='git pull'
alias memuse='ps -o rss,command | grep -v peruser | awk "{sum+=\$1} END {print sum/1024}"'